---
- name: install python tooling
  hosts: localhost
  connection: local
  tags:
    - python

  tasks:
  - name: ensure virtualenv (for pipsi)
    dnf: name=python-virtualenv state=present
    become: true

  - name: install pipsi
    shell: curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python
    args:
      creates: ~/.local/bin/pipsi

  - name: install python tools via pipsi
    shell: pipsi install {{ item }}
    args:
      creates: ~/.local/bin/{{ item }}
    with_items:
      - pew
      - pipenv
      - cookiecutter
    
- name: configure vagrant
  hosts: localhost
  connection: local
  tags:
    - devtools

  tasks:
  - name: install vagrant
    dnf: name={{ item }} state=present
    become: true
    with_items:
      - vagrant-libvirt
      - vagrant-hostmanager
      - vagrant-sshfs

