---
- hosts: localhost
  connection: local

  tasks:
  - name: python tools
    block:
    - name: install pipsi
      # using Python 3 because it's 2018 and it doesn't require virtualenv to be installed
      # curl causes a warning but I think this is cleaner than creating a temporary file
      shell: curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python3
      args:
        creates: ~/.local/bin/pipsi
  
    - name: install python tools via pipsi
      shell: pipsi install {{ item }}
      args:
        creates: ~/.local/bin/{{ item }}
      with_items:
        - pew
        - pipenv
        - cookiecutter
    tags:
      - python
    
  - name: install vagrant
    # add user to 'libvirt' group to avoid authentication prompts
    dnf: name={{ item }} state=present
    become: true
    with_items:
      - vagrant-libvirt
      - vagrant-hostmanager
      - vagrant-sshfs

    tags:
    - devtools

