---
# Installation of common programs and basic configuration
# TODO: how will Powerline work with PuTTY fonts? (should I break it out?)
- hosts: localhost
  connection: local

  tasks:
    - name: ensure pre-requisites
      dnf:
        name:
          - libselinux-python
        state: latest
      become: yes

    - name: install common apps
      dnf:
        name:
          - backintime-qt
          - git
          - htop
          - tmux
          - vim-enhanced
          - vim-powerline
          - tmux-powerline
          - zsh
        state: latest
      become: yes
      tags: common

    - name: install Oh My Zsh
      shell: "sh -c \"$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)\""
      args:
        creates: ~/.oh-my-zsh
      tags: common

    - name: Configure zsh
      copy:
        src: "zshrc"
        dest: "~/.zshrc"
        mode: 0644
      tags:
        - common
        - config

    - name: configure Vim
      block:
        - name: ensure Vim directories
          file:
            path: "~/.vim/{{ item }}"
            state: directory
          with_items:
            - autoload
            - backup
            - tmp
            - undodir

        - name: install vim-plug
          get_url:
            url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
            dest: ~/.vim/autoload/plug.vim

        - name: configure vim
          blockinfile:
            path: ~/.vimrc
            create: yes
            marker: "\" {mark} {{ item.description }}"
            block: "{{ item.text }}"
          with_items:
            - description: "plugins (vim-plug)"
              text: |
                call plug#begin('~/.vim/plugged')
                Plug 'pearofducks/ansible-vim'
                Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
                call plug#end()
                map <C-n> :NERDTreeToggle<CR>
            - description: "tabs"
              text: |
                set autoindent
                set expandtab
                set shiftwidth=4
                set smarttab
                set softtabstop=4
            - description: "editing"
              text: |
                set history=100
            - description: "search"
              text: |
                set ignorecase
                set incsearch
            - description: "display"
              text: |
                set scrolloff=6
                set cursorline
                set ruler
                set number
                set showcmd
                colorscheme elflord
                " highlight needs to go after colorscheme
                highlight CursorLine term=None cterm=None ctermbg=black
                set colorcolumn=80
            - description: "autocommands"
              text: |
                " copied from https://dougblack.io/words/a-good-vimrc.html
                augroup configgroup
                  " clear autocommands to prevent double processing
                  autocmd!
                  autocmd filetype text setlocal textwidth=78
                  autocmd filetype python setlocal colorcolumn=90
                  " close NERDTree
                  autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
                augroup END
            - description: "backups"
              text: |
                " Manage backups and swap files in a central location
                " NOTE: vim doesn't create the directories
                set backup
                set backupdir=~/.vim/backup
                set directory=~/.vim/tmp
            - description: "undo"
              text: |
                " Persistent undo.
                " NOTE: vim doesn't create the directories
                set undofile
                set undodir=~/.vim/undodir
            - description: "powerline"
              text: |
                " Helpful settings for the Powerline statusline
                " (ensures the status lines show up)
                set laststatus=2
                set showtabline=2
                set noshowmode
                " Fix for virtualenvs in Fedora 28-29 (should use variables/target)
                python3 sys.path.append('/usr/lib/python3.7/site-packages/')

      tags:
        - common
        - config

    - name: Configure htop
      block:
        - file:
            path: ~/.config/htop
            state: directory

        - copy:
            src: htoprc
            dest: ~/.config/htop/htoprc
      tags: config

    - name: Configure tmux
      copy:
        src: tmux.conf
        dest: ~/.tmux.conf
      tags: config

    - name: Copy global gitignore (need to configure manually)
      copy:
        src: gitignore
        dest: ~/.gitignore_global
      tags: config

