---
- hosts: localhost
  connection: local

  tasks:
    - name: python tools
      block:
        - name: install pipx (replacement for pipsi)
          pip:
            name: "pipx"
            state: "present"
            extra_args: "--user"
            virtualenv_python: "python3"
        - name: install python tools via pipx
          shell: pipx install {{ item }}
          args:
            creates: ~/.local/bin/{{ item }}
          with_items:
            - pew
            - pipenv
            - poetry
            - cookiecutter
            - tox
      tags:
        - python

    - name: Vagrant
      block:
        - name: ensure vagrant installed
          dnf:
            name:
              - "@vagrant"
              - "vagrant-hostmanager"
              - "vagrant-sshfs"
            state: present
          become: true
        - debug:
            msg: "Add user to 'libvirt' group to avoid authentication prompts"

      tags:
        - devtools
        - vagrant

    - name: Docker
      block:
        - name: ensure docker repository
          get_url:
            url: https://download.docker.com/linux/fedora/docker-ce.repo
            dest: /etc/yum.repos.d/docker-ce.repo
            mode: 0644
            owner: root
        - name: ensure docker installed
          dnf:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            state: present
            # In case stable doesn't support current version yet
            #enablerepo: docker-ce-edge
        - name: enable docker service
          systemd:
            name: docker
            enabled: true
            state: started
            daemon_reload: true
        - debug:
            msg: "Add user to 'docker' group to eliminate need to run as root/sudo"
      become: true
      tags:
        - devtools
        - docker

    - name: VS Code
      block:
        - name: Ensure VS Code repository
          copy:
            src: vscode.repo
            dest: /etc/yum.repos.d/vscode.repo
            owner: root
            group: root
            mode: 0644

        - name: Ensure Microsoft's repo key
          rpm_key:
            state: present
            key: https://packages.microsoft.com/keys/microsoft.asc

        - name: Ensure VS Code installed
          dnf:
            name: code
            state: present

      become: true
      tags:
        - devtools
        - vscode
