---
- hosts: localhost
  connection: local

  tasks:
  - name: ham radio tools
    dnf: 
      name:
        - aldo
        - chirp
        - fldigi
        - gqrx
        - js8call
        - qsstv
        - rtl-sdr
        - soapy-rtlsdr
        - wsjtx
      state: present
    become: true

    tags:
    - never
    - radio

