---
- hosts: localhost
  connection: local

  tasks:
  - name: ham radio tools
    dnf: 
      name:
        - aldo
        - fldigi
        - chirp
        - CubicSDR
        - rtl-sdr
        - soapy-rtlsdr
        - qsstv
      state: present
    become: true

    tags:
    - radio

